[build]
  # Build command for frontend only
  command = "npm run build"
  
  # Output directory  
  publish = "dist"
  
  # Environment variables
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"
    # API URL will be set in Netlify dashboard
    VITE_API_URL = "https://your-backend-url.com/api"

[dev]
  # Local dev server settings
  command = "npm run dev"
  port = 5173
  publish = "dist"

# Redirects for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; font-src 'self' data:;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Netlify Functions (for future API endpoints)
[functions]
  directory = "netlify/functions"